package com.dinamoproductions.wowow.server.http;

public class StatusCodes {
	public static String SC_ACCEPTED = "202 Accepted";
	public static String SC_BAD_GATEWAY = "502 Bad Gateway";
	public static String SC_BAD_REQUEST = "400 Bad Request";
	public static String SC_CONFLICT = "409 Conflict";
	public static String SC_CONTINUE = "100 Continue";
	public static String SC_CREATED = "201 Created";
	public static String SC_EXPECTATION_FAILED = "417 Expectation Failed";
	public static String SC_FAILED_DEPENDENCY = "424 Failed Dependency";
	public static String SC_FORBIDDEN = "403 Forbidden";
	public static String SC_FOUND = "302 Found";
	public static String SC_GATEWAY_TIMEOUT = "504 Gateway Timeout";
	public static String SC_GONE = "410 Gone";
	public static String SC_HTTP_VERSION_NOT_SUPPORTED = "505 HTTP Version Not Supported";
	public static String SC_INSUFFICIENT_STORAGE = "507 Insufficient Storage";
	public static String SC_INTERNAL_SERVER_ERROR = "500 Server Error";
	public static String SC_LENGTH_REQUIRED = "411 Length Required";
	public static String SC_LOCKED = "423 Locked";
	public static String SC_METHOD_NOT_ALLOWED = "405 Method Not Allowed";
	public static String SC_MOVED_PERMANENTLY = "301 Moved Permanently";
	public static String SC_MOVED_TEMPORARILY = "302 Moved Temporarily";
	public static String SC_MULTI_STATUS = "207 Multi-Status";
	public static String SC_MULTIPLE_CHOICES = "300 Multiple Choices";
	public static String SC_NO_CONTENT = "204 No Content";
	public static String SC_NON_AUTHORITATIVE_INFORMATION = "203 Non Authoritative Information";
	public static String SC_NOT_ACCEPTABLE = "406 Not Acceptable";
	public static String SC_NOT_FOUND = "404 Not Found";
	public static String SC_NOT_IMPLEMENTED = "501 Not Implemented";
	public static String SC_NOT_MODIFIED = "304 Not Modified";
	public static String SC_OK = "200 OK";
	public static String SC_PARTIAL_CONTENT = "206 Partial Content";
	public static String SC_PAYMENT_REQUIRED = "402 Payment Required";
	public static String SC_PRECONDITION_FAILED = "412 Precondition Failed";
	public static String SC_PROCESSING = "102 Processing";
	public static String SC_PROXY_AUTHENTICATION_REQUIRED = "407 Proxy Authentication Required";
	public static String SC_REQUEST_ENTITY_TOO_LARGE = "413 Request Entity Too Large";
	public static String SC_REQUEST_TIMEOUT = "408 Request Timeout";
	public static String SC_REQUEST_URI_TOO_LONG = "414 Request-URI Too Long";
	public static String SC_REQUESTED_RANGE_NOT_SATISFIABLE = "416 Requested Range Not Satisfiable";
	public static String SC_RESET_CONTENT = "205 Reset Content";
	public static String SC_SEE_OTHER = "303 See Other";
	public static String SC_SERVICE_UNAVAILABLE = "503 Service Unavailable";
	public static String SC_SWITCHING_PROTOCOLS = "101 Switching Protocols";
	public static String SC_TEMPORARY_REDIRECT = "307 Temporary Redirect";
	public static String SC_UNAUTHORIZED = "401 Unauthorized";
	public static String SC_UNPROCESSABLE_ENTITY = "422 Unprocessable Entity";
	public static String SC_UNSUPPORTED_MEDIA_TYPE = "415 Unsupported Media Type";
	public static String SC_USE_PROXY = "305 Use Proxy";

}
